github-actions:
  - changed-files:
    - any-glob-to-any-file: 
      - ./.github/**
      - ./.gitignore
back-end:
  - changed-files:
    - any-glob-to-any-file:
      - ./tailwind.config.mjs
      - ./tsconfig.json
      - ./package.json
      - ./package-lock.json
      - ./astro.config.mjs
content-change:
  - changed-files:
    - any-glob-to-any-file:
      - ./src/**
