name: Congratsbot

on:
  push:
    branches: [master]

jobs:
  congrats:
    name: congratsbot
    if: ${{ github.repository_owner == 'Okanagan-iGEM' }}
    uses: withastro/automation/.github/workflows/congratsbot.yml@main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CONGRATS }}
